-- V1__init.sql
-- Migración inicial: Crea las tablas roles, users y user_roles

-- Tabla de roles
CREATE TABLE roles (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(30) UNIQUE NOT NULL
);

-- Tabla de usuarios
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(150) NOT NULL,
  email VARCHAR2(150) UNIQUE NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Tabla intermedia para la relación ManyToMany entre users y roles
CREATE TABLE user_roles (
  user_id NUMBER NOT NULL REFERENCES users(id),
  role_id NUMBER NOT NULL REFERENCES roles(id),
  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);
