-- V1__init.sql (H2 compatible)
-- Migración inicial: Crea la tabla laboratorios

-- Tabla de laboratorios
CREATE TABLE laboratorios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  direccion VARCHAR(250),
  telefono VARCHAR(20)
);

-- Índice para búsquedas por nombre
CREATE INDEX idx_laboratorios_nombre ON laboratorios(nombre);
