-- V2__create_asignaciones.sql (H2 compatible)
-- Migración: Crea la tabla asignaciones con relación a laboratorios

-- Tabla de asignaciones
CREATE TABLE asignaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente VARCHAR(200) NOT NULL,
  fecha DATE NOT NULL,
  laboratorio_id BIGINT NOT NULL,
  CONSTRAINT fk_asignaciones_laboratorio FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
);

-- Índices para mejorar consultas
CREATE INDEX idx_asignaciones_fecha ON asignaciones(fecha);
CREATE INDEX idx_asignaciones_laboratorio ON asignaciones(laboratorio_id);
