-- V2__create_asignaciones.sql
-- Migración: Crea la tabla asignaciones con relación a laboratorios

-- Tabla de asignaciones
CREATE TABLE asignaciones (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  paciente VARCHAR2(200) NOT NULL,
  fecha DATE NOT NULL,
  laboratorio_id NUMBER NOT NULL,
  CONSTRAINT fk_asignaciones_laboratorio FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
);

-- Índices para mejorar consultas
CREATE INDEX idx_asignaciones_fecha ON asignaciones(fecha);
CREATE INDEX idx_asignaciones_laboratorio ON asignaciones(laboratorio_id);
