-- ============================================================
-- LABCONTROL: Schema Completo de Base de Datos
-- ============================================================
-- Sistema: LabControl - Sistema de Gestión de Laboratorios
-- Base de datos: Oracle Cloud ATP
-- Fecha: 2025
-- ============================================================

-- ============================================================
-- MS-USERS: Usuarios y Roles
-- ============================================================

-- Tabla de roles del sistema
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) UNIQUE NOT NULL
);

COMMENT ON TABLE roles IS 'Roles del sistema para control de acceso';

-- Tabla de usuarios
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE users IS 'Usuarios del sistema';

-- Tabla intermedia para la relación ManyToMany entre users y roles
CREATE TABLE user_roles (
    user_id NUMBER NOT NULL REFERENCES users(id),
    role_id NUMBER NOT NULL REFERENCES roles(id),
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

COMMENT ON TABLE user_roles IS 'Relación muchos a muchos entre usuarios y roles';

-- Índices ms-users
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_enabled ON users(enabled);

-- ============================================================
-- MS-LABORATORIOS: Laboratorios y Asignaciones
-- ============================================================

-- Tabla de laboratorios clínicos
CREATE TABLE laboratorios (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(250),
    telefono VARCHAR2(20)
);

COMMENT ON TABLE laboratorios IS 'Laboratorios clínicos registrados en el sistema';

-- Índice para búsquedas por nombre
CREATE INDEX idx_laboratorios_nombre ON laboratorios(nombre);

-- Tabla de asignaciones de pacientes a laboratorios
CREATE TABLE asignaciones (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    paciente VARCHAR2(200) NOT NULL,
    fecha DATE NOT NULL,
    laboratorio_id NUMBER NOT NULL,
    CONSTRAINT fk_asignaciones_laboratorio FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
);

COMMENT ON TABLE asignaciones IS 'Asignaciones de pacientes a laboratorios para análisis';

-- Índices ms-laboratorios
CREATE INDEX idx_asignaciones_fecha ON asignaciones(fecha);
CREATE INDEX idx_asignaciones_laboratorio ON asignaciones(laboratorio_id);

-- ============================================================
-- MS-RESULTS: Tipos de Análisis y Resultados
-- ============================================================

-- Tabla de tipos de análisis de laboratorio
CREATE TABLE tipos_analisis (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50) NOT NULL,
    unidad_medida VARCHAR2(20),
    valor_referencia_min NUMBER(10, 2),
    valor_referencia_max NUMBER(10, 2),
    activo NUMBER(1) DEFAULT 1 NOT NULL CHECK (activo IN (0, 1))
);

COMMENT ON TABLE tipos_analisis IS 'Catálogo de tipos de análisis clínicos disponibles';

-- Índices tipos_analisis
CREATE INDEX idx_tipos_analisis_nombre ON tipos_analisis(nombre);
CREATE INDEX idx_tipos_analisis_categoria ON tipos_analisis(categoria);
CREATE INDEX idx_tipos_analisis_activo ON tipos_analisis(activo);

-- Tabla de resultados de análisis
CREATE TABLE resultados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente VARCHAR2(200) NOT NULL,
    fecha_realizacion TIMESTAMP NOT NULL,
    tipo_analisis_id NUMBER NOT NULL,
    laboratorio_id NUMBER NOT NULL,
    valor_numerico NUMBER(10, 2),
    valor_texto VARCHAR2(500),
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    observaciones VARCHAR2(1000),
    creado_en TIMESTAMP NOT NULL,
    actualizado_en TIMESTAMP,
    CONSTRAINT fk_resultados_tipo_analisis FOREIGN KEY (tipo_analisis_id) REFERENCES tipos_analisis(id)
);

COMMENT ON TABLE resultados IS 'Resultados de análisis clínicos de pacientes';

-- Índices resultados
CREATE INDEX idx_resultados_paciente ON resultados(paciente);
CREATE INDEX idx_resultados_laboratorio ON resultados(laboratorio_id);
CREATE INDEX idx_resultados_estado ON resultados(estado);
CREATE INDEX idx_resultados_fecha ON resultados(fecha_realizacion);

-- ============================================================
-- FIN DEL SCHEMA
-- ============================================================
