-- ============================================================
-- MS-LABORATORIOS: Schema de Base de Datos
-- ============================================================
-- Microservicio: ms-laboratorios (Puerto 8082)
-- Base de datos: Oracle Cloud ATP
-- Descripcion: Gestión de laboratorios y asignaciones
-- ============================================================

-- Tabla de laboratorios clínicos
CREATE TABLE laboratorios (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(250),
    telefono VARCHAR2(20)
);

COMMENT ON TABLE laboratorios IS 'Laboratorios clínicos registrados en el sistema';
COMMENT ON COLUMN laboratorios.id IS 'Identificador único del laboratorio';
COMMENT ON COLUMN laboratorios.nombre IS 'Nombre del laboratorio';
COMMENT ON COLUMN laboratorios.direccion IS 'Dirección física del laboratorio';
COMMENT ON COLUMN laboratorios.telefono IS 'Teléfono de contacto';

-- Índice para búsquedas por nombre
CREATE INDEX idx_laboratorios_nombre ON laboratorios(nombre);

-- Tabla de asignaciones de pacientes a laboratorios
CREATE TABLE asignaciones (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    paciente VARCHAR2(200) NOT NULL,
    fecha DATE NOT NULL,
    laboratorio_id NUMBER NOT NULL,
    CONSTRAINT fk_asignaciones_laboratorio FOREIGN KEY (laboratorio_id) REFERENCES laboratorios(id)
);

COMMENT ON TABLE asignaciones IS 'Asignaciones de pacientes a laboratorios para análisis';
COMMENT ON COLUMN asignaciones.id IS 'Identificador único de la asignación';
COMMENT ON COLUMN asignaciones.paciente IS 'Nombre del paciente';
COMMENT ON COLUMN asignaciones.fecha IS 'Fecha de la asignación';
COMMENT ON COLUMN asignaciones.laboratorio_id IS 'Laboratorio asignado';

-- Índices para mejorar consultas
CREATE INDEX idx_asignaciones_fecha ON asignaciones(fecha);
CREATE INDEX idx_asignaciones_laboratorio ON asignaciones(laboratorio_id);
