-- ============================================================
-- MS-USERS: Schema de Base de Datos
-- ============================================================
-- Microservicio: ms-users (Puerto 8081)
-- Base de datos: Oracle Cloud ATP
-- Descripcion: Gestión de usuarios, roles y autenticación
-- ============================================================

-- Tabla de roles del sistema
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) UNIQUE NOT NULL
);

COMMENT ON TABLE roles IS 'Roles del sistema para control de acceso';
COMMENT ON COLUMN roles.id IS 'Identificador único del rol';
COMMENT ON COLUMN roles.name IS 'Nombre del rol (ADMIN, LAB_TECH, DOCTOR)';

-- Tabla de usuarios
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE users IS 'Usuarios del sistema';
COMMENT ON COLUMN users.id IS 'Identificador único del usuario';
COMMENT ON COLUMN users.full_name IS 'Nombre completo del usuario';
COMMENT ON COLUMN users.email IS 'Email único del usuario (usado para login)';
COMMENT ON COLUMN users.password_hash IS 'Contraseña del usuario';
COMMENT ON COLUMN users.enabled IS 'Estado del usuario (1=activo, 0=inactivo)';
COMMENT ON COLUMN users.created_at IS 'Fecha de creación del usuario';

-- Tabla intermedia para la relación ManyToMany entre users y roles
CREATE TABLE user_roles (
    user_id NUMBER NOT NULL REFERENCES users(id),
    role_id NUMBER NOT NULL REFERENCES roles(id),
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

COMMENT ON TABLE user_roles IS 'Relación muchos a muchos entre usuarios y roles';

-- Índices para mejorar rendimiento
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_enabled ON users(enabled);
