-- V1__init.sql
-- Migración inicial: Crea la tabla laboratorios

-- Tabla de laboratorios
CREATE TABLE laboratorios (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(150) NOT NULL,
  direccion VARCHAR2(250),
  telefono VARCHAR2(20)
);

-- Índice para búsquedas por nombre
CREATE INDEX idx_laboratorios_nombre ON laboratorios(nombre);
